name: finance_control
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.1
  google_fonts: ^5.1.0
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  google_mobile_ads: ^3.0.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Montserrar
      fonts:
        - asset: lib/0_core/fonts/Montserrar-Light.ttf
          weight: 300
        - asset: lib/0_core/fonts/Montserrar-Regular.ttf
          weight: 400
        - asset: lib/0_core/fonts/Montserrar-Medium.ttf
          weight: 500
        - asset: lib/0_core/fonts/Montserrar-Bold.ttf
          weight: 700
        - asset: lib/0_core/fonts/Montserrar-ExtraBold.ttf
          weight: 800
        - asset: lib/0_core/fonts/Montserrar-Black.ttf
          weight: 900
