name: finance_control
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+14

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.4
  permission_handler: ^8.3.0
  shimmer: ^3.0.0
  uuid: ^3.0.7
  clipboard: ^0.1.3
  google_mobile_ads: ^3.0.0
  in_app_purchase: ^3.1.10

  finance_control_ui:
    path: ../finance_control_ui/
    # git: "https://github.com/danielmaques/finance_control_ds.git"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/langs/
    
flutter_intl:
  enabled: true
