// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwJcMbrBuATYpYAYhbcKpWVmy0vGX3pE',
    appId: '1:513199116842:android:637ab91ec66bc0d1f5a953',
    messagingSenderId: '513199116842',
    projectId: 'finance-control-77d24',
    databaseURL: 'https://finance-control-77d24-default-rtdb.firebaseio.com',
    storageBucket: 'finance-control-77d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6wa22GESRq1NyZg_Tejyactc8ZQ6lWU',
    appId: '1:513199116842:ios:8f07a352865c8adbf5a953',
    messagingSenderId: '513199116842',
    projectId: 'finance-control-77d24',
    databaseURL: 'https://finance-control-77d24-default-rtdb.firebaseio.com',
    storageBucket: 'finance-control-77d24.appspot.com',
    androidClientId: '513199116842-uh2skeu50s62beoad7o2e60e5fdj92he.apps.googleusercontent.com',
    iosClientId: '513199116842-kpv3qmdldfftndcesjgeq9ja3l79g0q3.apps.googleusercontent.com',
    iosBundleId: 'dev.dm8.financeControl',
  );
}
