import 'package:finance_control_ui/finance_control_ui.dart';
import 'package:flutter/material.dart';
import 'package:flutter_modular/flutter_modular.dart';

class ShowAddAccount extends StatefulWidget {
  const ShowAddAccount({
    super.key,
    required this.controller,
  });

  final dynamic controller;

  @override
  State<ShowAddAccount> createState() => _ShowAddAccountState();
}

class _ShowAddAccountState extends State<ShowAddAccount> {
  final ValueNotifier<List<dynamic>> categoriesList =
      ValueNotifier<List<dynamic>>([
    "Conta corrente",
    "Conta poupança",
    "Conta empresarial",
  ]);

  List<String> banks = [
    "American Express",
    "Mastercard",
    "Visa",
    "Credicard",
    "Diners",
    "Elo",
    "Nubank",
    "Aura",
    "Inter",
    "Banco do Brasil",
    "Bradesco",
    "Caixa",
    "Hipercard",
    "Itaú",
    "Neon",
    "Next",
    "Nuconta",
    "Santander",
    "Agibank",
    "Amazonia",
    "Ame Digital",
    "BMG",
    "BRB",
    "BRDE",
    "BS2",
    "BTG Pactual",
    "Cacique",
    "PAN",
    "Votorantim",
    "Banco do Nordeste",
    "Banese",
    "Banestes",
    "Banif",
    "Banpara",
    "Banrisul",
    "Bbm",
    "Cetelem",
    "Citibank",
    "Clear",
    "Cruzeirodosul",
    "Daycoval",
    "Digi+",
    "Digio",
    "Diin",
    "Nuinvest",
    "Elliot",
    "Fortbrasil",
    "Genial Investimentos",
    "HSBC",
    "IQ Option",
    "Iti",
    "Magnetis",
    "Mais!",
    "Mercadopago",
    "ModalMais",
    "Moip",
    "Monetus",
    "N26",
    "Nova Futura",
    "Original",
    "Pag!",
    "PagBank",
    "Pagseguro",
    "PayU Brasil",
    "Paypal",
    "PicPay",
    "Recargapay",
    "Rico",
    "Safra",
    "Sicoob",
    "Sicredi",
    "Sodexo",
    "Sofisa direto",
    "Submarino",
    "Toro Investimentos",
    "Unicred",
    "Uniprime",
    "Urbe.Me",
    "Viacredi",
    "ABN AMRO",
    "AGBank",
    "AKBank",
    "AMP Personal Banking",
    "ANZ",
    "ASN",
    "Absolut Bank",
    "Agribank",
    "Aktia",
    "Alfa",
    "Alpha",
    "Americanas",
    "Ameriprise Financial",
    "Attica",
    "BBVA",
    "BCA",
    "BIDV",
    "BMO",
    "BNI",
    "BNL",
    "BNP Paribas",
    "BOQ",
    "BPER Banca",
    "BPI",
    "BRI",
    "Banamex",
    "Banca Carige",
    "Banca DItalia",
    "Banca MPS",
    "Banca Mediolanum",
    "Banca Populare di Sondrio",
    "BPM",
    "Banco de Bogotá",
    "Banco de Occident",
    "Banco del Bajio",
    "Posta",
    "lombia",
    "Bangkok Bank",
    "Bank Norwegian",
    "Bank Rakyat",
    "Bank of Aland",
    "Bank of America",
    "Bank of China",
    "Bankia",
    "Bankwest",
    "Banorte",
    "Barclays",
    "Ben Visa Vale",
    "Bendigo",
    "C6 Bank",
    "CDB",
    "CDP",
    "CIBC",
    "CIMB Bank",
    "CIMB Niaga",
    "CTT",
    "Caisse dEpargne",
    "Caixa Geral",
    "CaixaBank",
    "Capital One",
    "Carteira",
    "Cassa Depositi e Prestiti",
    "Charles Schwab",
    "China Construction",
    "CommBank",
    "Commerzbank",
    "Credit Bank of Moscow",
    "Credit agricole",
    "Credito Emiliano",
    "Crédit Agricole",
    "Crédit du Nord",
    "DNB",
    "DZ Bank",
    "Danske",
    "Davivienda",
    "Default",
    "Deutsche Bank",
    "Eurobank",
    "Evli",
    "Forex",
    "Galicia",
    "Garanti",
    "Gazprombank",
    "Goldman Sachs",
    "Handelsbanken",
    "Hipotecario",
    "Hong Leong",
    "HypoVereinsbank",
    "ICBC",
    "ICCREA Banca",
    "ING",
    "Inbursa",
    "Intesa Sanpaolo",
    "Isbank",
    "JP",
    "JP Morgan Chase",
    "Jyske",
    "KB Kookmin",
    "KBank",
    "KDB",
    "KEB Hana",
    "KFW",
    "Krung Thai Bank",
    "Lloyds Banking Group",
    "MUFG",
    "Macquarie",
    "Macro",
    "Mandiri",
    "Maybank",
    "MedioBanca",
    "Millenium BCP",
    "Mizuho",
    "Morgan Stanley",
    "NAB",
    "NH",
    "Nación",
    "National Bank of Greece",
    "Nochu",
    "Nordea",
    "Nordnet",
    "Novo Banco",
    "Nykredit",
    "OP",
    "Otkritie",
    "PNC Financial Services",
    "Patagonia",
    "Piraeus",
    "Porto Seguro",
    "Promsvyazbank",
    "Public Bank",
    "RBC Royal",
    "RBS",
    "RHB",
    "Rabobank",
    "Raiffeisen Bank",
    "Revolut",
    "SCB",
    "SEB",
    "SMBC",
    "SMP Bank",
    "SNS",
    "Sabadell",
    "Santander Espanha",
    "Santander México",
    "Sberbank",
    "Scotiabank",
    "Senff",
    "Shinhan",
    "Société Générale",
    "Sparebank 1 SMN",
    "Standard Chartered",
    "Storebrand",
    "Suncorp",
    "Superdigital",
    "Swedbank",
    "SydBank",
    "TD Bank",
    "TMB Bank",
    "Techcombank",
    "Tesouro Direto",
    "Tesouro Nacional",
    "Ticket",
    "Tinkoff",
    "TransferWise",
    "Trigg",
    "UBI Banca",
    "US Bank",
    "Unicredit Bank",
    "Unipol Banca",
    "UrPay",
    "VTB",
    "Vietcombank",
    "VietinBank",
    "Warren",
    "Wells Fargo",
    "Westpac",
    "Woop",
    "Xdex",
    "Xp Investimentos",
    "Yapi Kredi Bank",
    "Ziraat",
    "alelo",
    "bunq",
    "Órama",
    "Flash",
    "Cora",
    "Will",
    "UTIL",
    "Caju",
    "Outros"
  ];

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      scrollable: true,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      title: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          FinanceText.h4(
            'Nova conta',
            fontWeight: FontWeight.w500,
          ),
          IconButton(
            onPressed: () {
              Modular.to.pop();
            },
            icon: Icon(
              Icons.close_rounded,
              size: 20,
              color: Colors.grey[400],
            ),
          ),
        ],
      ),
      content: Column(
        children: [
          FinanceTextField(
            hintText: 'Instituição financeira',
            textCapitalization: TextCapitalization.sentences,
            onChanged: (p0) {
              widget.controller.bank.value = p0;
            },
            validator: (p0) {
              if (widget.controller.bank.value.isEmpty) {
                return 'Insira uma instituição financeira';
              }
              return null;
            },
          ),
          const SizedBox(height: 24),
          FinanceDropDown(
            hint: "Tipo de conta",
            categoriesList: categoriesList,
            onItemSelected: (p0) {
              widget.controller.account.value = p0;
            },
          ),
          const SizedBox(height: 24),
          FinanceDropDown(
            hint: "Selecione o proprietário",
            categoriesList: widget.controller.users,
            onItemSelected: (p0) {
              widget.controller.userSelect.value = p0;
            },
          ),
          const SizedBox(height: 24),
          FinanceButton(
            title: 'Salvar',
            onTap: () {
              setState(() {
                widget.controller.getAccountBanks();
              });
              if (widget.controller.bank.value.isNotEmpty) {
                widget.controller.addBank();
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    backgroundColor: AppColors.forestGreen,
                    content: Text('Conta adicionada'),
                  ),
                );
                Modular.to.pop();
              }
            },
          ),
        ],
      ),
    );
  }
}
